version: '3.4'
services:
  ddb:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.dolphindb
    image: ddb:sjddb
    volumes:
      - /data/sjddb/local8848:/opt/ddb/server/local8848
      - ./ddb/server/dbcache:/opt/ddb/server/dbcache
    container_name: ddb-sjddb
    restart: always
    network_mode: "host"